# Generated by Django 4.0.4 on 2022-05-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_student_name_student_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='user',
            new_name='users',
        ),
    ]
